### ISSUE TITLE
Feature: Hide Shortcut

### ISSUE THREAD

**Issue by reustle** [Nosrac/Dictater#1]
When I right click and dictate something, I don't always want to see the popup. It would be nice to either be able to disable this auto popup completely, or a quick shortcut to click the "done" button

**Comment by Nosrac** [comment]
I'm not completely sure I understand.  You want to hide the Dictater interface when dictating text?  In your mind, how would you open the interface once it was closed?

**Comment by reustle** [comment]
I'm not exactly sure I guess :) , I just find myself closing out the little window frequently when all I really want is to hear the spoken text and move on.

**Comment by Nosrac** [comment]
I'm still thinking about the best way to do this.

Dictater doesn't put an icon in your dock so hiding the window will just permanently keep Dictater in memory without any UI.

If I could lower the opacity of the window when it wasn't active would that work as a solution?

**Comment by reustle** [comment]
I don't think changing the opacity is any different than the current implementation. Not saying the current form is bad, just that this is how I use it. Maybe I'll just grow to ignore it and close it later :)

**Comment by jlaurrieta** [comment]
wouldn´t it just be esasier to use osx speech feature rather than Dictater in this case? After all, what you're proposing is just to disable the features Dictater offers...

**Comment by reustle** [comment]
You are correct. I'm on El Capitan now and simply use the context menu option now. Happy to close this issue (feature?).
