### ISSUE TITLE
Is there any way to use Dictator in Preview?

### ISSUE THREAD

**Issue by tarvos21** [Nosrac/Dictater#15]
Great App, thanks for making this.
I know Dictator does not support PDF, but is there any way, i.e., through settings of either GUI or command or script, that makes it work in Preview? I know some basic terminal skills. The Apps I use most on Mac are Safari and Preview, I find Dictator really great for reading stuff in Safari, better than the built-in Text-to-Speech function, so I have the question. If the answer is no, it's OK, I'll just close the issue. Thanks for reading.

**Comment by Nosrac** [comment]
Hey, 

I don't think Dictater would be able to do something like that.  Here's a potential workaround though:

If you can select the text in your PDF, copy that to another app (TextEdit for example), and paste it there.  From there you should be able to select the text and click 'Dictate'.

Let me know if that doesn't work

**Comment by tarvos21** [comment]
Yes,  it works, thanks for advice, I will close this.
