### ISSUE TITLE
Hangs using OS 10.13.2

### ISSUE THREAD

**Issue by FCD706** [Nosrac/Dictater#19]
Speech begins and quickly hangs.

**Comment by weiweiwei33** [comment]
I'm experiencing the same issue :(

**Comment by bigsmile01** [comment]
I have this issue on 10.13.3

**Work around:**
1. Open "Activity Monitor". 
2. Search for _com.apple.speech.speechsynthesisd_ and force quit.
3. Resend the text from your document to Dictate (no need to quit Dictate).

Interestingly, when following this work around, 90% of the time, you can resend the same text that caused it to hang in the first place and it will play just fine.
For the other 10% of the time it will hang again. But if you send a smaller amount of text it will work.

It's not clear what the limit on the amount of words you can send before it hangs. It almost seems to be random.

**Comment by FCD706** [comment]
I guess my stuff is all in the 10%. Thanks anyway.

**Comment by bigsmile01** [comment]
The issue seems to be with the voice Alex. I deleted all voices from my Mac and then used Daniel (UK) and it seems to work now. If I reinstall Alex and try it, then it hangs again.

**Comment by Nosrac** [comment]
Sorry for the stupid-long delay in my reply.  I've updated the app for Catalina, let me know if it works for you now (assuming you still care!)

**Comment by bigsmile01** [comment]
@Nosrac 
It's like Christmas, I'm so thrilled Dictator has been updated. I am still on Mojave. But the new Dictator seems to work! Thanks for your efforts.
