### ISSUE TITLE
Can not find Dictate under Prefrences>Keyboard>Shortcuts>Text

### ISSUE THREAD

**Issue by aziz** [Nosrac/Dictater#2]
I'm using 10.11 El capitan and installed dictater using brew cask

**Comment by Nosrac** [comment]
Hey Aziz, I'll investigate this soon.  Until then, can you confirm something for me?
- Is the app installed inside /Applications/ ?  I'm not sure but I think Services might require this

**Comment by martijnengler** [comment]
I have the same issue. I've installed the app in the /Applications folder (before opening it).

**Comment by aziz** [comment]
Ok, `brew cask` does not install into `/Applications/` by default. It could but current formula installs it in default location which is `/opt/homebrew-cask/Caskroom/dictater/`.

I don't like to install apps into /Applications/ using drag and drop but I might do it for Dictater if there's no other way to get it to work.

**Comment by Nosrac** [comment]
Hey guys,

I uninstalled Dictater from my machine tried to make OS X forget about it.  I had a few bumps but I think it worked.  I then installed Dictater via Cask.  It seemed to work for me once I opened the application (from ~/Applications).

Earlier, I assumed you guys opened the app before checking System Preferences.  Is that the case?  I'm not sure but I believe Apple requires that before I can register the service.

**Comment by aziz** [comment]
I didn't get what you mean exactly, but I removed and reinstalled the app using cask. it still installs the app in `/opt/homebrew-cask/Caskroom/dictater/` but creates a symlink in `~/Applications`.

I used that symlink to open the app but it still can not register the service and I can not find `Dictate` under text services.

**Comment by Nosrac** [comment]
Hmmm.. Unfortunately this is hard for me to test because I don't have any 'blank slate' computers.

Would you mind trying something out for me? Install Dictater to /Applications and then open it there.  I'm not 100% sure but if that fixes the problem I _think_ you can remove it from /Applications and your cask installation will work.

That's obviously not a perfect solution but I would like to know if a band-aid exists.

Thanks

**Comment by adriweb** [comment]
Hey Kyle :)
My current OS X setup (10.11, 15A282a) is Dictater-free (for now) so if you want me to test something on a "clean slate" machine, tell me what to do!

**Comment by martijnengler** [comment]
I don't know what happened, but after opening Dictater again (without reinstalling, doing an update etc.) it now shows up for me.

For the record: I didn't install via cask in the first place, and just installed in to /Applications right away. If there's any way I can help with logs or anything to debug this… Just let me know. :)

**Comment by Nosrac** [comment]
Interesting.  Thanks for the follow up
