### ISSUE TITLE
Dictater Pause not working after MacOs upgrade to 10.15.1 Catalina

### ISSUE THREAD

**Issue by blimto5** [Nosrac/Dictater#21]
After upgrading MacOs I found Dictator will pause for 5-10 seconds, then reset to beginning.
The ability to pause is the main feature I like in this product. Hoping your kind attention is turned to fixing this -- you don't realize how much you need something until it's not there.

John

**Comment by Nosrac** [comment]
Thanks for the heads up John, I'll look into this in the next few days.

**Comment by blimto5** [comment]
Very much appreciated Kyle.
I use Dictater *a lot* and really value the app.

John

**Comment by Nosrac** [comment]
Hey again, sorry I haven't gotten to this yet.  This is a particularly busy time of the year for me.  I should have time to fix this in the next month.

**Comment by blimto5** [comment]
Thanks again Kyle. I (and many others) really appreciate any time you can spare.

John

**Comment by FlavourDave92** [comment]
Is there a way to work around? It really is some kind of a show stopper when it forgets the current state of the dictation :/

**Comment by Nosrac** [comment]
Sorry I haven't gotten around to this.  I should have time in the next few days given COVID-19.

@FlavourDaveMasterDDissle-theDtotheissle @blimto5

**Comment by Nosrac** [comment]
@blimto5 @FlavourDaveMasterDDissle-theDtotheissle 

Sorry again for the leaving this for so long.  The good news is it works again!  Download the release here: https://github.com/Nosrac/Dictater/releases/tag/catalina

NOTE:  The progress bar is no longer available.  I'll look into adding this in later but I wanted to get this out ASAP.

**Comment by FlavourDave92** [comment]
Very Nice, Thank you so much! on a side note: "Check for Updates" still says:

![image](https://user-images.githubusercontent.com/5797170/77194085-8fbcfc80-6adf-11ea-9bc3-39e91074d18d.png)

**Comment by thespacedoctor** [comment]
Hi there, I have downloaded the 1.2.1 version linked above but still this same issue persists. Having paused, after 1-2 sec the document resets to the start. Also find that Dictater is reporting it is still at version 1.2.

**Comment by Nosrac** [comment]
@thespacedoctor Sorry about that.  At this point, this code is old enough that I want to rewrite it and give the interface an overhaul.  I'll get that done in February.
