### ISSUE TITLE
Upgrade to latest Swift Version

### ISSUE THREAD

**Issue by tleish** [Nosrac/Dictater#22]
@Nosrac, I use this app on a frequent basis and would like some minor enhancements.  It appears this is on an old version of swift.  If you could upgrade to the latest Swift version, I could try to pitch in and work on some of the bug fixes and/or enhancements.

**Comment by Nosrac** [comment]
Thanks for the ofer @tleish.  I'll see if I can carve out some time to get this project updated to the latest Swift version in the next few weeks.
Kyle

**Comment by tleish** [comment]
FYI, I attempted upgrading to Swift 4.2.  Swift is new to me, but I
basically went though XCode and accepted a good portion of the suggested
changed of renamed methods, etc.  I think I've done most of the easy work,
the harder stuff remains (although, who knows... I may have messed up the
entire project).

See my swift4.2 branch
https://github.com/tleish/Dictater/tree/swift4.2

**Comment by Nosrac** [comment]
Hey again @tleish,

Sorry I didn't get back to your last message 🙈.

Just wanted to let you know I finally carved out some time and got the app working again.  You can download here: https://github.com/Nosrac/Dictater/releases/tag/catalina

**Comment by tleish** [comment]
Awesome!  Thank you for updating.
