### ISSUE TITLE
Play/Pause Shortcut

### ISSUE THREAD

**Issue by Fabula84** [Nosrac/Dictater#9]
First off, I want to say I'm loving this app. Thank you for the work!

My issue is I would like to assign hot keys to some of the functions in the app (I looked through the issues, open and closed, and didn't see this listed, but I apologize if it has been stated somewhere). Basically, if I'm working on revisions in a word processor (or even while in Read Along mode, which I notice has a CMD 1 shortcut), I'd like to be able to hit a shortcut on my keyboard to pause the dictation, make a correction, then unpause the dictation. It would be nice to set hot keys for the Skip and Skip Backward features, too, but being able to pause it instantly instead of using the mouse cursor would save time and frustration.

I look forward to a response. Thanks again!

**Comment by Fabula84** [comment]
Any word? I've spend some time trying to get automator to automate a hotkey to toggle pause and play, and I've encountered nothing but failure. I'm also pretty terrible at programing of any kind, so I'm still hoping there's a solution.

**Comment by Nosrac** [comment]
Hey @Fabula84, there isn't a perfect way to do this right now, I'll try to add the feature soon.

Here's an AppleScript that you could drop into an Automator workflow for the meantime:

```
on run {input, parameters}

    set theApp to ((path to frontmost application) as text)

    activate application "Dictater"
    tell application "System Events" to keystroke " "

    activate theApp

    return input
end run
```

**Comment by Fabula84** [comment]
Awesome, that did the trick precisely. Thanks so much!
